Repository depromeet/pingpong-client, pull requests merged in 2022-11, with the labels that each got.

#12 :bug: fix: Remove comma at prlabeler.yml
  .github/pr-labeler-config.yml
Labels: bug

#13 fix: Remove yarnPath config at yarnrc to fix nodeLinker error
  .yarnrc.yml
  yarn.lock
Labels: bug

#17 📦 chore: tailwind configuration
  .vscode/css_custom_data.json
  .vscode/settings.json
  package.json
  postcss.config.js
  src/pages/_app.tsx
  yarn.lock
Labels: chore

#18 ✨ feature: add category selection hook
  next.config.js
  src/hooks/useCategorySelection.tsx
Labels: enhancement

#26 :sparkles: add useQuery & useMutation hooks & fetch function
  src/apis/index.ts
  src/hooks/test.ts
  src/lib/utils.ts
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: chore

#31 :package: install axios
  package.json
  yarn.lock
Labels: bug

#39 ✨ feature: add profile img
  src/components/common/ProfileImg.tsx
Labels: enhancement

#50 :bug: fix: storybook svg import error
  .storybook/main.js
  package.json
  yarn.lock
Labels: bug

#49 :sparkles: checkbox component
  .storybook/main.js
  src/components/common/CheckBox.stories.tsx
  src/components/common/CheckBox.tsx
  src/components/common/icons/Check.tsx
  src/components/common/icons/index.ts
  src/lib/utils.ts
Labels: enhancement

#52 :sparkles: feat: add toast component
  src/components/common/Button.tsx
  src/components/common/Layout.tsx
  src/components/common/Toast.tsx
  src/store/components/atoms.ts
  src/typings/common.d.ts
  tailwind.config.js
  yarn.lock
Labels: enhancement

#53 :recycle: refactor: merge navigation component & devide icons folder
  src/components/common/NavigationBar.tsx
  src/components/common/NavigationBarList.tsx
  src/components/icons/Check.tsx
  src/components/icons/ProfileIcon.tsx
  src/components/icons/TalentRegisterIcon.tsx
  src/components/icons/TalentSearchIcon.tsx
  src/components/icons/index.ts
Labels: refactor

#55 :sparkles: feat: add color palette
  src/apis/index.ts
  src/components/common/CheckBox.tsx
  src/components/common/Input.tsx
  src/components/common/Tag.stories.tsx
  src/components/common/Tag.tsx
  src/components/common/Toast.tsx
  src/constants/components.ts
  tailwind.config.js
Labels: enhancement

#62 :recycle: refactor(storybook): Add classification common components
  src/components/common/Button.stories.tsx
  src/components/common/CheckBox.stories.tsx
  src/components/common/Input.stories.tsx
  src/components/common/Tag.stories.tsx
Labels: refactor
