Repository depromeet/pingpong-client, pull requests merged in 2022-12, with the labels that each got.

#65 :sparkles: feat: profile page
  public/icons/modify.svg
  public/icons/setting.svg
  public/images/ranking.png
  src/components/common/TextBox.stories.tsx
  src/components/common/TextBox.tsx
  src/pages/profile/index.tsx
  src/styles/globals.css
Labels: enhancement

#98 :sparkles: feat: setting page pub
  public/icons/setting-arrow.svg
  src/components/common/Header.tsx
  src/components/common/Radio.tsx
  src/hooks/usePopup.ts
  src/pages/profile/index.tsx
  src/pages/profile/setting.tsx
  src/pages/setting/alarm.tsx
  src/typings/common.d.ts
Labels: enhancement

#106 Fix: type errors
  src/components/common/Card.tsx
  src/components/common/CardCarousel.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Input.tsx
  src/components/common/Popup.tsx
  src/components/common/Textarea.tsx
  src/components/main/MainCategoryCarousel.tsx
  src/components/main/MainCategoryItem.tsx
  src/hooks/queries/useInfinitePostsQuery.ts
  src/store/components/atoms.ts
  src/typings/MainCategoryInfo.d.ts
Labels: bug

#105 :sparkles: feat: Add setting interface
  src/components/common/Radio.tsx
  src/pages/profile/setting.tsx
  src/pages/setting/alarm.tsx
  src/typings/interface.d.ts
Labels: enhancement

#93 :sparkles: feat: Add lottie spinner at global layout
  package.json
  public/spinner.json
  src/components/common/Layout.tsx
  src/components/common/Spinner.tsx
  src/pages/index.tsx
  src/store/components/atoms.ts
  yarn.lock
Labels: enhancement

#110 :package: chore: Change baseUrl of axiosClient
  src/apis/index.ts
Labels: chore

#111 :bug: fix: Fix using wrong baseurl at axios
  next.config.js
  src/apis/index.ts
Labels: bug

#117 :bug: fix: env file
  dist/dev/404.html
  dist/dev/_next/static/chunks/236-87b4e096c9e1325b.js
  dist/dev/_next/static/chunks/332-e6b3a806aabb6068.js
  dist/dev/_next/static/chunks/664-1b4479b4462ded63.js
  dist/dev/_next/static/chunks/main-bc1a515a011ad0f9.js
  dist/dev/_next/static/chunks/pages/_app-bd7a1fdb8ec7a98b.js
  dist/dev/_next/static/chunks/pages/index-4ca8ff070c35fec0.js
  dist/dev/_next/static/chunks/pages/login-330ad198275099a2.js
  dist/dev/_next/static/chunks/pages/nickname-a0e85c8dad282de6.js
  dist/dev/_next/static/chunks/pages/playground-9b261c488289734a.js
  dist/dev/_next/static/chunks/pages/profile-485ef6772164b07f.js
  dist/dev/_next/static/chunks/pages/talent/register-2e5a4d6ac3fcdd0e.js
  dist/dev/_next/static/chunks/pages/talent/register/exchange-5067adc99c27a9af.js
  dist/dev/_next/static/chunks/pages/talent/register/share-8173b68d2e869185.js
  dist/dev/_next/static/chunks/webpack-a4f8b795d2eb4d91.js
  dist/dev/_next/static/css/4ff1da3b7875a074.css
  dist/dev/_next/static/vfvWJv896pUwC2QlkmZpF/_buildManifest.js
  dist/dev/_next/static/vfvWJv896pUwC2QlkmZpF/_ssgManifest.js
  dist/dev/index.html
  dist/dev/login.html
  dist/dev/nickname.html
  dist/dev/playground.html
  dist/dev/profile.html
  dist/dev/talent/register.html
  dist/dev/talent/register/exchange.html
  dist/dev/talent/register/share.html
  package.json
  yarn.lock
Labels: enhancement

#122 :sparkles: feat: Add Env file to main
  .github/workflows/dev-firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
Labels: enhancement

#126 :bug: fix: Remove wrong file format included at tsconfig
  tsconfig.json
Labels: bug

#127 :bug: fix: Fix react query fetch error
  src/components/common/Layout.tsx
  src/components/common/NavigationBar.tsx
  src/components/common/Popup.tsx
  src/hooks/queries/useCustomPostsQuery.ts
  src/hooks/queries/useInfinitePostsQuery.ts
  src/hooks/queries/useUserInfoQuery.ts
  src/hooks/test.ts
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/pages/dev.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/main.tsx
Labels: enhancement

#130 Fix: 게시글 상세 페이지 안나오는 이슈
  next.config.js
  src/hooks/queries/useCategoriesQuery.ts
  src/hooks/queries/useCustomPostsQuery.ts
  src/hooks/queries/useInfinitePostsQuery.ts
  src/hooks/queries/usePostLikeMutate.ts
  src/hooks/queries/usePostQuery.ts
  src/hooks/queries/usePostUnlikeMutate.ts
  src/hooks/queries/useUserInfoQuery.ts
  src/pages/posts/[id].tsx
Labels: bug

#124 :sparkles: feat: Add Nickname page
  src/apis/index.ts
  src/components/common/CircleCheckbox.tsx
  src/hooks/queries/useNicknameMutate.ts
  src/pages/nickname.tsx
Labels: enhancement

#131 Feature/modal block
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/Popup.tsx
  src/components/talentRegister/TalentRegisterCategoryHeader.tsx
  src/components/talentRegister/TalentRegisterHeader.tsx
  src/hooks/useHeader.ts
  src/hooks/usePopup.ts
  src/hooks/usePopupWithBlock.ts
  src/hooks/useTab.ts
  src/pages/profile/edit/givenTalents/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/profile/edit/takenTalents/index.tsx
  src/pages/profile/setting/index.tsx
  src/pages/setting/alarm.tsx
  src/pages/setting/index.tsx
  src/store/components/atoms.ts
  src/typings/common.d.ts
Labels: enhancement

#137 :recycle: refactor: Update baseURL
  next.config.js
  src/apis/index.ts
  src/hooks/queries/useCategoriesQuery.ts
  src/hooks/queries/useCustomPostsQuery.ts
  src/hooks/queries/useInfinitePostsQuery.ts
  src/hooks/queries/usePostLikeMutate.ts
  src/hooks/queries/usePostQuery.ts
  src/hooks/queries/usePostUnlikeMutate.ts
  src/hooks/queries/useUserInfoQuery.ts
Labels: enhancement

#132 :sparkles: feat: Add user info
  src/hooks/queries/useMyInfoQuery.ts
  src/hooks/queries/useUserInfoQuery.ts
  src/pages/main.tsx
  src/pages/profile/edit/index.tsx
  src/store/components/atoms.ts
Labels: enhancement
